# Site wide configuration

title: Dos Piruletas
description: Scrapbooking
#logo: # 120x120 px default image used for Twitter summary card
#teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: "http://maribeltg.github.io/blog/"

# Jekyll configuration

markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Maribel
  email: scrapdospiruletas@gmail.com
  twitter: dospiruletas
  google:
    ad-client: xxxxxx
    ad-slot: xxxxxx
  bio: Algo que poner
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: dospiruletas


#exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
